### PR TITLE
attempt to permit user target language

### PR DESCRIPTION
**Pull request by SlovaDev**
@R-V-S

### CODE REVIEW

**Comment by R-V-S** [comment]
@SlovaDev 

After looking into this, I think the "problem" lies with Angular2-Token. I don't think it's transmitting `target_lang`. 

No matter what I change in Rails, these are the parameters that it sees:

```
Parameters: {"email"=>"a@c.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "confirm_success_url"=>"http://localhost:3000/#/new_user", "registration"=>{"email"=>"a@c.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "confirm_success_url"=>"http://localhost:3000/#/new_user"}}
```

No `target_lang`.

And if you look at the documentation for [.registerAccount()](https://www.npmjs.com/package/angular2-token#registeraccount), it seems to only expect an object with the following params: email, password, passwordConfirmation, and an optional userType.

Seems like Angular2-Token is pretty limited in this respect. 

It does have a general purpose [.request()](https://www.npmjs.com/package/angular2-token#registeraccount) method, though. Might be necessary to utilize that for passing back/forth anything more than the most basic user data.

If I'm right (which I'm not positive about), then saving `target_lang` on user sign up would need to be a 2-step process: First you register the user (`.registerAccount`), and then, inside the `res` function of user sign-up, you use the A2-Token's `request` method to update the account info.

**Comment by SlovaDev** [comment]
Thanks Raj, I was actually thinking about the same thing, updating the user's language in another request. However, I'm unable to grab the current user provided by Devise's `include DeviseTokenAuth::Concerns::SetUserByToken`, `current_user` is always nil. Do you think this has anything to do with the fact that I am inheriting my `ApplicationController` from `ActionController::API`?

**Comment by R-V-S** [comment]
@SlovaDev 
Sounds like it might be the problem, but where are you trying to use `current_user`? I don't see any instances of it in the branch that I have (on `user_scoping`)

**Comment by SlovaDev** [comment]
@R-V-S I was trying to access the `current_user` in the `TranslationsController` which inherits from `ApplicationController`, so I'd assume that I'd have access to it there as well. Just pushed the code I've been working on. Also created a `UsersController` which I'd need if I want to add that `target_language` param to the user after registration, in which I'd define an #update action and send the HTTP request to that route.

Not sure if [this](https://github.com/lynndylanhurley/devise_token_auth/issues/28) issue log conversation would help but I've been reading through it with little success. Thanks for looking into this with me

**Pull request merged**
